#!/bin/bash


if [ "$(id -u)" != "0" ]; then
   echo "Script must be run as root !"
   exit 0
fi

echo ""
date
echo "********************************"
echo "Update u-boot in sdcard image   "
echo "********************************"
echo ""

# =====================================================
# ==== P A R A M E T E R S ============================
# =====================================================

# *********************
# Set sdcard image name
# *********************
sdcardimg="jessie-minimal.img"


# *****************************************************
# Path to odroid u-boot files
# *****************************************************
BL1="uboot/bl1.bin.hardkernel"
UBOOT="uboot/u-boot.bin"

# ^^^^ P A R A M E T E R S ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

if [ ! -f $BL1 ]; then
    echo "Error: $BL1 is not exist."
    exit 0
fi

if [ ! -f $UBOOT ]; then
    echo "Error: $UBOOT is not exist."
    exit 0
fi


echo ""
echo "Updating u-boot in $sdcardimg ..."
dd if=$BL1 of=${sdcardimg} bs=1 count=442 conv=notrunc > /dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "ERROR installing u-boot."
    exit 0
fi
dd if=$BL1 of=${sdcardimg} bs=512 skip=1 seek=1 conv=notrunc > /dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "ERROR installing u-boot."
    exit 0
fi
dd if=$UBOOT of=${sdcardimg} bs=512 seek=64 conv=notrunc > /dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "ERROR installing u-boot."
    exit 0
fi
sync

echo ""
echo "U-boot updated in $sdcardimg."
# -------------------------------------------------------------------
    
# -------------------------------------------------------------------
